name: Digger CI/CD

on:
  pull_request:
    branches: [ main ]
  issue_comment:
    types: [created]

jobs:
  digger:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      id-token: write
      pull-requests: write
      issues: read
      statuses: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform and Terragrunt
        run: |
          # Install Terraform using direct download
          TERRAFORM_VERSION="1.6.0"
          wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          
          # Install Terragrunt
          TERRAGRUNT_VERSION="0.80.4"
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          
          # Verify installations
          terraform version
          terragrunt version
      
      - name: Run Digger Plan (PR) or Apply (Comment)
        uses: diggerhq/digger@v0.6.126
        with:
          setup-aws: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          no-backend: true
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}