name: Digger CI/CD

on:
  pull_request:
    branches: [ main ]
  issue_comment:
    types: [created]

jobs:
  digger:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      id-token: write
      pull-requests: write
      issues: read
      statuses: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Terragrunt
        run: |
          wget -q -O /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.80.4/terragrunt_linux_amd64
          chmod +x /usr/local/bin/terragrunt
          terragrunt --version
      
      - name: Generate Terragrunt Stack
        run: |
          cd prod/us-east-1/s3-stack
          terragrunt --experiment stacks stack generate
          ls -la .terragrunt-stack/s3_bucket/
      
      - name: Run Digger Plan (PR) or Apply (Comment)
        uses: diggerhq/digger@v0.6.126
        with:
          setup-aws: true
          setup-terraform: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          no-backend: true
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}